### ISSUE TITLE
Implement correct refactoring for Groovy files

### ISSUE THREAD

**Issue by edmondo1984** [bonitasoft/bonita-studio#1]
From Groovy official website

>Refactoring Support for Groovy-Eclipse Plugin

> As result of a bachelor thesis at the HSR University of Applied Sciences Rapperswil, > Institute for Software, three students had implemented refactoring features for the Groovy- Eclipse plugin.

Is there a known reason why in Bonita Studio refactoring has been custom implemented as a **"find and replace"** feature that can mess up all the code?

See source /src/org/bonitasoft/studio/common/refactoring/BonitaGroovyRefactoringAction.java 

I am wondering how a software engineer could imagine of writing a refactoring for a weakly typed programming language in 163 lines of Java code, without even differentiating between a string constant and a method name.

Even worse, I am wondering how a company can let this feature be shipped to a final customer while it took three bachelor thesis for other guys to develop it

**Comment by apupier** [comment]
Hi,

Groovy support refactoring is based on Groovy-Eclipse refactoring since the 6.3.0 version, see http://www.bonitasoft.com/node/13373?download=true

Regards,
