### ISSUE TITLE
Canvas object coordinates in the graph drawing widget are incorrect for many objects

### ISSUE THREAD

**Issue by dumblob** [bonitasoft/bonita-studio#3]
I encountered on my desktop the following graphical issue with BonitaBPMCommunity-6.4.2 (downloaded as an x86_64 binary from bonitasoft web page):

![2015-03-05-083545_1680x1050 0 0_imlib2_grab_98dpi](https://cloud.githubusercontent.com/assets/2451044/6551819/ae45e05e-c63e-11e4-8b8e-ddea63ad0488.png)

![2015-03-05-083900_1680x1050 0 0_imlib2_grab_130dpi](https://cloud.githubusercontent.com/assets/2451044/6551881/9262ab50-c63f-11e4-9c17-0e7dfd31b937.png)

(showing an imported graph https://github.com/dumblob/tmp/blob/master/PV165_projekt_Truhlarstvi-201502281130.bos)

Other Java applications (including *Eclipse 4.4.1*) run fine (disregarding if they're using their own bundled version of Java or the system one, which is in my case *jre7-openjdk 7.u75_2.5.4*).

It seems to be an issue with the drawing canvas (the other artifacts in widgets are just a matter of Java being unable to properly mimic the GTK theme - but this is not an issue for me). I've tried changing DPI (the first screenshot is 98 DPI and the second one 130 DPI), but obviously without any effect. Neither changing the desktop environment and window managers (KDE, Gnome, FVWM, Karmen) had any effect.

Any idea how to fix it?

**Comment by apupier** [comment]
Hi,

we never encountered this kind of issue.

can you specify which version of Linux you are using?

You might try to use Yakindu (http://www.statecharts.org/) which is using quite the same underlying technology than us in order to see if the issue come from one Eclipse components or is specfiic to Bonita.

Regards,

**Comment by dumblob** [comment]
>can you specify which version of Linux you are using?

Linux t500 3.14.33-1-lts #1 SMP Fri Feb 13 17:02:25 CET 2015 x86_64 GNU/Linux

I've followed the instructions on http://www.statecharts.org/download.html and this is the result of *File -> New -> Example -> YAKINDU Examples -> Trafficlight Example*:

![2015-03-09-103457_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/6552673/aa7c5d86-c648-11e4-9349-499761514dbf.png)

![2015-03-09-104108_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/6552678/d37a2150-c648-11e4-9141-0924916be9bf.png)

As demonstrated on the second picture, I can zoom the canvas, move objects, resize them, interact with them etc. without any glitches. On the other hand, I don't know if Bonita BPM uses also Eclipse Luna.

**Comment by apupier** [comment]
Hi,

Bonita is using since version 6.5.0 which was released few hours ago. Would you kindly mind to test with this new version please?

Thanks for taking time to report details on this issue.

**Comment by dumblob** [comment]
I've installed the new version 6.5.0, but unfortunately it exits (with the exit code *0*) about 5 seconds after the main window
![2015-03-14-212316_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/6653395/465bd078-ca91-11e4-8039-2fec8bab1e83.png)
shows up. Also immediately when the main window shows up, the HDD activity increases to 100% and the main window is not responsive.

The terminal output (even when using the *-verbose* flag) is:
~~~~
Starting Groovy-Eclipse compiler resolver.  Specified compiler level: unspecified
364 1.8.6.xx-201411061335-e44-RELEASE = STARTING
No bp log location saved, using default.
No bp log location saved, using default.
[000:000] Browser XEmbed support present: 1
[000:002] Browser toolkit is Gtk2.
[000:003] Using Gtk2 toolkit
~~~~

**Comment by apupier** [comment]
It seems that you are using oxygen theme which is not compatible with Eclipse when opening a dialog (a registration dialog open at startup of Bonita product). See https://bugs.eclipse.org/bugs/show_bug.cgi?id=440660

**Comment by dumblob** [comment]
Even though I'm not using any Oxygen theme (neither any derivation of it), I've tested it with the Default GTK2 theme (the ugly-looking one) several times and it always ends up as I described in my previous post https://github.com/bonitasoft/bonita-studio/issues/3#issuecomment-80713425 .
![2015-03-16-125031_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/6665607/b8d49c98-cbdb-11e4-8cfa-297f5607f961.png)

The *Help* button is risen, because in the first half a second, Bonita BPM reacts as expected (i.e. after closing the initial registration dialog by clicking on Cancel), but then in gets stuck due to sudden high HDD activity. I haven't found anything like that in the Eclipse bugzilla :(

Also, according to *top*, the load of one of my real CPU cores is 100% (at the same time as the HDD load) and is used by about 3 threads from all the threads (about 20) ran by Bonita BPM.

**Comment by apupier** [comment]
Can you check if you have other log in workspace/.metadata/.log please?
Another Eclipse issue known is https://bugs.eclipse.org/bugs/show_bug.cgi?id=428975
You should have some more details in the mentioned log files if you hit this bug.

Can you take 2 Thread dumps at around 10 seconds intervals when it occurs please? https://helpx.adobe.com/experience-manager/kb/TakeThreadDump.html

**Comment by dumblob** [comment]
>Can you check if you have other log in workspace/.metadata/.log please?

There seems to be everything OK:
~~~~
!SESSION 2015-03-16 13:04:44.869 -----------------------------------------------
eclipse.buildId=6.5.0.
java.version=1.7.0_55
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Framework arguments:  --launcher.XXMaxPermSize512m -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 --launcher.XXMaxPermSize512m -clearPersistedState -data /home/test/.local/share/bonitasoft/bonita-bpm-community-6.5.0/workspace

!ENTRY org.eclipse.core.resources 2 10035 2015-03-16 13:04:49.030
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.bonitasoft.studio.engine 1 0 2015-03-16 13:04:52.025
!MESSAGE Starting tomcat...

!ENTRY org.bonitasoft.studio.engine 1 0 2015-03-16 13:04:52.062
!MESSAGE Starting studio watchdog on 6969

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-16 13:05:13.543
!MESSAGE Startup duration : 00:00:24
~~~~
All other log sections (corresponding to one run of Bonita BPM) look the same. I.e. no exceptions, no errors, nothing suspicious. Btw I'm running Bonita BPM from the directory I installed it to (using `./*.run --mode unattended --prefix '/opt/bonitasoft/bonita650'`) with arguments `-configuration "$HOME/.config/bonitasoft/bonita650"` and `-data "$HOME/.local/share/bonitasoft/bonita-bpm-community-6.5.0/workspace"`.

The very first run of Bonita BPM was of course a bit more verbose:
~~~~
!SESSION 2015-03-13 15:44:47.042 -----------------------------------------------
eclipse.buildId=6.5.0.
java.version=1.7.0_55
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Framework arguments:  --launcher.XXMaxPermSize512m -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 --launcher.XXMaxPermSize512m -clearPersistedState -data /home/test/.local/share/bonitasoft/bonita-bpm-community-6.5.0/workspace

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:04.867
!MESSAGE Updating RSS feed:6-3-blogs.xml

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:04.867
!MESSAGE Updating RSS feed:6-3-community.xml

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:04.867
!MESSAGE Updating RSS feed:6-3-documentation.xml

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:04.867
!MESSAGE Updating RSS feed:6-3-examples-community.xml

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:04.868
!MESSAGE Updating RSS feed:6-3-training.xml

!ENTRY org.bonitasoft.studio.common.repository 1 0 2015-03-13 15:45:04.885
!MESSAGE Creating repository default...

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:04.887
!MESSAGE Updating RSS feed:6-3-videos.xml

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:04.894
!MESSAGE Initializing BONITA.HOME

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.005
!MESSAGE Configuring bonita client on host localhost:8080 with API_TYPE=HTTP

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.008
!MESSAGE BONITA.HOME installed.

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.021
!MESSAGE Opening project: default

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:05.031
!MESSAGE RSS feed:6-3-examples-community.xml updated successfuly!

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:05.031
!MESSAGE RSS feed:6-3-training.xml updated successfuly!

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:05.032
!MESSAGE RSS feed:6-3-documentation.xml updated successfuly!

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:05.032
!MESSAGE RSS feed:6-3-videos.xml updated successfuly!

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:05.032
!MESSAGE RSS feed:6-3-community.xml updated successfuly!

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:05.032
!MESSAGE RSS feed:6-3-blogs.xml updated successfuly!

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.057
!MESSAGE Cannot retrieve the JavaProject Nature from the project: default

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.071
!MESSAGE Plan to add Project Nature org.bonitasoft.studio.common.repository.bonitaNature

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.072
!MESSAGE Plan to add Project Nature org.eclipse.xtext.ui.shared.xtextNature

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.072
!MESSAGE Plan to add Project Nature org.eclipse.jdt.groovy.core.groovyNature

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.072
!MESSAGE Plan to add Project Nature org.eclipse.jdt.core.javanature

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.072
!MESSAGE Plan to add Project Nature org.eclipse.pde.PluginNature

!ENTRY org.bonitasoft.studio.common 1 0 2015-03-13 15:45:05.073
!MESSAGE Setting Project Descritor with natures:[Ljava.lang.String;@33df9b77

!ENTRY org.bonitasoft.studio.engine 1 0 2015-03-13 15:45:05.073
!MESSAGE Copying tomcat bundle in workspace...

!ENTRY org.bonitasoft.studio.engine 1 0 2015-03-13 15:45:05.598
!MESSAGE Tomcat bundle copied in workspace.

!ENTRY org.bonitasoft.studio.engine 1 0 2015-03-13 15:45:05.598
!MESSAGE Starting tomcat...

!ENTRY org.bonitasoft.studio.engine 1 0 2015-03-13 15:45:05.621
!MESSAGE Starting studio watchdog on 6969

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.711
!MESSAGE Initializing repository with Database driver.

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.717
!MESSAGE Initializing repository with h2-1.3.170.jar Database driver

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.732
!MESSAGE Initializing repository with derby.jar Database driver

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.757
!MESSAGE Initializing repository with ojdbc6.jar Database driver

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.781
!MESSAGE Initializing repository with sqlite-jdbc-3.7.2.jar Database driver

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.794
!MESSAGE Initializing repository with postgresql-9.2-1002.jdbc4.jar Database driver

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.801
!MESSAGE Initializing repository with sqljdbc4.jar Database driver

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.807
!MESSAGE Initializing repository with hsqldb.jar Database driver

!ENTRY org.bonitasoft.studio.connectors.database.drivers 1 0 2015-03-13 15:45:10.820
!MESSAGE Initializing repository with mysql-connector-java-5.1.23-bin.jar Database driver

!ENTRY org.bonitasoft.studio.common.repository 1 0 2015-03-13 15:45:13.053
!MESSAGE Updating build path...

!ENTRY org.bonitasoft.studio.common.repository 1 0 2015-03-13 15:45:28.654
!MESSAGE Repository default created in 00:00:23

!ENTRY org.bonitasoft.studio.application 1 0 2015-03-13 15:45:35.927
!MESSAGE Startup duration : 00:00:33
!SESSION 2015-03-13 15:47:48.232 -----------------------------------------------
...
~~~~

**Comment by dumblob** [comment]
Starting from Bonita BPM 6.5.1, I got few more messages on stdout/stderr:
~~~~
...
364 1.8.6.xx-201411061335-e44-RELEASE = STARTING
No bp log location saved, using default.
No bp log location saved, using default.
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:000] Using Gtk2 toolkit
~~~~
And after some googling, I found [similar](https://bugs.eclipse.org/bugs/show_bug.cgi?id=334466) older [issues](https://bugs.eclipse.org/bugs/show_bug.cgi?id=349837#c14). It appears, the temporary workaround is to put
~~~~ini
-Dorg.eclipse.swt.browser.DefaultType=mozilla
~~~~
into the `BonitaBPMCommunity.ini` file. On my system, this results in a blank "page" instead of the web page showed e.g. when running on Windows 8.1, but at least the whole Bonita BPM appears to work like a charm.

Another good news is, that the canvas problem with drawing widgets is not any more present and thus it's finally possible to fully use Bonita BPM under Linux/X11 systems.

I'll close this issue, as I don't consider the XULrunner problem as a big deal - I'm pretty OK with the blank page:

![2015-04-12-145340_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/7105653/e6461212-e123-11e4-9501-2dd2ca422435.png)

But of course, for other customers, the initial dashboard page might be a must-have.

**Comment by apupier** [comment]
thank you for the follow-up on the issue and to share your solution with us.
Just for information, on more classical distribution (Ubuntu), the welcome page is working since Bonita 6.5+

**Comment by dumblob** [comment]
>Just for information, on more classical distribution (Ubuntu), the welcome page is working since Bonita 6.5+

Well, it seems to be due to an old SW in Ubuntu and thus differences in library naming - namely the webkit libraries, which are on my Arch Linux system called:

~~~~
0$ ls -1 /usr/lib/libwebkit*
/usr/lib/libwebkitgtk-1.0.so
/usr/lib/libwebkitgtk-1.0.so.0
/usr/lib/libwebkitgtk-1.0.so.0.22.14
/usr/lib/libwebkitgtk-3.0.so
/usr/lib/libwebkitgtk-3.0.so.0
/usr/lib/libwebkitgtk-3.0.so.0.22.14
/usr/lib/libwebkit2gtk-4.0.so
/usr/lib/libwebkit2gtk-4.0.so.37
/usr/lib/libwebkit2gtk-4.0.so.37.2.6
~~~~

Some more information can be found in https://bbs.archlinux.org/viewtopic.php?id=115543 and https://wiki.archlinux.org/index.php/Eclipse#Troubleshooting . By the way, Eclipse has no issues with help (i.e. embedded browser) on my system and I didn't have to configure anything (and according to the eclipse package, it uses the `/usr/lib/libwebkitgtk-1.0*` library).
