### ISSUE TITLE
platform/original_platform.target 

### ISSUE THREAD

**Issue by saeiddrv** [bonitasoft/bonita-studio#357]
Hi

`<repository location="http://www.jspresso.org/external/updates-snapshot/e44"/>`
All plugins in this location have 404 Error!

**Comment by rbioteau** [comment]
Hi,
a lot of repositories we are using to build our target platform may not be maintained properly (it happens a lot saddly with p2 repositories). That s why we always mirror the content of the target platform each time we change it.
You can check the documentation page here: http://documentation.bonitasoft.com/building-bonita-bpm-source-files-1
Mirror for latest release is here: http://update-site.bonitasoft.com/p2/7.0/
