### ISSUE TITLE
bonita-studio build problem

### ISSUE THREAD

**Issue by JamesAngel** [bonitasoft/bonita-studio#399]
Hi when I attempt to build bonita-studio using maven I get following error: 

`
[ERROR] Failed to resolve target definition /home/James/bonita/bonita-studio/platform/platform.target: Failed to load p2 metadata repository from location http://repositories.rd.lan/p2/7.3: Unknown Host: http://repositories.rd.lan/p2/7.3/content.xml: Unknown host repositories.rd.lan -> [Help 1]
`
It seems that repository "http://repositories.rd.lan/p2/7.3" does not exists. What must I do?

**Comment by Nicodonald** [comment]
Same thing here. Seems that repositories.rd.lan is a local repo the tld .lan is not routable.
Is there a way to add a public repository, to compile bonita studio from source ?

**Comment by alachambre** [comment]
Hello,

Check this repository, it provides a script to build our product. 
https://github.com/Bonitasoft-Community/Build-Bonita

We update it frequently to ensure it still work, let us know if you find any problems!
Adrien

**Comment by Nicodonald** [comment]
Thanks but I have an issue with a p2 repository located in an internal
network apparently
I opened a ticket there
