### ISSUE TITLE
UI Designer objects not display, only tabs container and form container exists on ui designer

### ISSUE THREAD

**Issue by mskutlu** [bonitasoft/bonita-studio#400]
Hello, 
There is a bug in program. I was able to find the problem and partially solved. Problem is when i installed bonita software everything works but in ui designer there is no object shows, only tabs container and form container. I searched but i couldn't find anything. I tried to create custom widget and i got an error. 

This is the error. 
> Could not read JSON: Can not construct instance of org.bonitasoft.web.designer.model.widget.PropertyType, problem: No enum constant org.bonitasoft.web.designer.model.widget.PropertyType.CHOİCE at [Source: java.io.PushbackInputStream@54e35b8c; line: 1, column: 2382] (through reference chain: org.bonitasoft.web.designer.model.widget.Widget["properties"]->java.util.ArrayList[1]->org.bonitasoft.web.designer.model.widget.Property["type"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.bonitasoft.web.designer.model.widget.PropertyType, problem: No enum constant org.bonitasoft.web.designer.model.widget.PropertyType.CHOİCE at [Source: java.io.PushbackInputStream@54e35b8c; line: 1, column: 2382] (through reference chain: org.bonitasoft.web.designer.model.widget.Widget["properties"]->java.util.ArrayList[1]->org.bonitasoft.web.designer.model.widget.Property["type"])

Well problem is my OS was in Turkish language and i saw this part in error. "designer.model.widget.PropertyType.CHOİCE"
In turkish language capital i letter is "İ" but in english it is "I". I changed the language of my OS then it worked.

**Comment by rbioteau** [comment]
Can you report the issue in the [Bugtracker](https://bonita.atlassian.net) ?
Thanks for your contribution
